### ISSUE TITLE
Info button

### ISSUE THREAD

**Issue by polyfluid** [jackturner/voice#11]
Hello Jack,

Please add the text below to the info area:

The robots in the intallation, You’ll Never Know We Were Here, are designed to create an anonymous protest, continuously moving protest signs up and down. Unlike their human counterparts, these robot activists do not have identities, they do not worry about reprisal for broadcasting their messages. The voice you leave on this website may become part of the protest during the exhibition of this artwork at the Spring Break Art Show in New York City.

**Comment by oliviaartz** [comment]
I put this info in issue #5 and closes this one as a duplicate.
