### ISSUE TITLE
link the site to domain name

### ISSUE THREAD

**Issue by polyfluid** [jackturner/voice#12]
I took out to domain names for this site, 

robotprotest.com
protestrobot.com

oh.. wait... once you are finished with the site, we will upload it to my server... yes. this issue is done.

**Comment by oliviaartz** [comment]
Yeah, or I can do a thing to have it hosted by GitHub the same way they're hosting it now at https://jackturner.github.io/voice/… but at either of the domains you want above. Or we can drop it on your server. I think the page will load faster if it's on GitHub, but then you can only have it at one domain. (But you can still redirect one of them to the other.)

In any case, this is a good issue to have so we don't forget to, you know… put the site live at the right domain(s).

**Comment by polyfluid** [comment]
Lets leave it on GitHub so it can be easier to update in the future. I can point the domains to place it is now... let me see if I can make that happen on my iPower.com
