### ISSUE TITLE
facebook and twitter share

### ISSUE THREAD

**Issue by polyfluid** [jackturner/voice#22]
In the info area, can we add an icon to share the project on facebook and twitter? 

Also, now that we switched it to the domain name, will that bit where the video shows up and autoplays work? I tried but didn't seem to work...

**Comment by polyfluid** [comment]
Maybe it needs time to link itself so that the preview shows up...

**Comment by oliviaartz** [comment]
Good idea. I'll add twitter and facebook links.

Yeah, that video should work. I'll look into it.
