### ISSUE TITLE
Spreadsheet 

### ISSUE THREAD

**Issue by polyfluid** [jackturner/voice#23]
Is there anyway we can make the verification of posts easier? Just did it with my phone and it was sort of annoying. Is there a little hidden page you can make that I can press on yes or no? I ask because I’ll likely not have laptop access while the show is on... I’ll be approving while I’m on the go. Let me know if that is doable.

**Comment by polyfluid** [comment]
Also, is there a way to send me notifications of when new posts are up? Like an email? Oh! Maybe in the email I say yes or no? Is that doable?

**Comment by polyfluid** [comment]
A text would be the nest, but I suspect that is wicked hard..

**Comment by oliviaartz** [comment]
You can turn on notifications right from within Google Docs!

Just go to the ``Tools`` menu and choose `Notification rules…`
![image](https://user-images.githubusercontent.com/15309/35835001-3f61b3de-0aa6-11e8-9fd5-3881f3e75ba4.png)

Then set it to email your right away with any changes…
![image](https://user-images.githubusercontent.com/15309/35835051-823ea4e6-0aa6-11e8-9cc6-83432ddae2a4.png)

As far as editing goes, have you tried the [Google Sheets app](https://itunes.apple.com/us/app/google-sheets/id842849113?mt=8)? Or is that still cumbersome? Haven't used it recently enough to know.
