### ISSUE TITLE
Show some sort of response/confirmation when something is submitted

### ISSUE THREAD

**Issue by oliviaartz** [jackturner/voice#9]

**Comment by polyfluid** [comment]
Your Protest has been received! It will reviewed and be posted soon.

Maybe that?

**Comment by polyfluid** [comment]
Oops... misspelled something.

Your Protest has been received! 
It will be reviewed and posted soon.

Adding the above means that the refresh time for reseting the page should go up. Like maybe 8 seconds?

**Comment by oliviaartz** [comment]
I made it 6 seconds. Feels better to me.
